### ISSUE TITLE
some codes problem

### ISSUE THREAD

**Issue by chouqin3** [qsyao/attack_landmark_detection#1]
Your network framwork as follows
```
        _, features = self.vgg.features(x, get_features=True)

        x = self.up1(features[4], features[3])
        x = self.up2(x, features[2])
        x = self.up3(x, features[1])
        x = self.up4(x, features[0])
        x = self.up5(x)

        x = self.final(x)
        
        heatmap = F.sigmoid(x[:,:self.n_classes,:,:])
        regression_x = x[:,self.n_classes:2*self.n_classes,:,:]
        regression_y = x[:,2*self.n_classes:,:,:]
```
There is no skip connection in the code, conflicts with your paper. Besides, self.vgg.features(x, get_features=True) cannot be executed,  the compiler error is that got an unexpected keyword argument get_features

**Comment by qsyao** [comment]
Thank you for your interest.

I temporary change the source code of class Sequential in pytorch to get the feature from VGG, which serve as the skip connection in U-Net.

In readme: 
Get features from VGG19
cp container.py venv/lib/python3.6/site-packages/torch/nn/modules
We add another arg to torch.nn.Sequitial. This change will not cause other conficts.

Although it is a little bit stupid, but easy enough. I used to set a individual environment for each projects.

**Comment by chouqin3** [comment]
> Thank you for your interest.
> 
> I temporary change the source code of class Sequential in pytorch to get the feature from VGG, which serve as the skip connection in U-Net.
> 
> In readme:
> Get features from VGG19
> cp container.py venv/lib/python3.6/site-packages/torch/nn/modules
> We add another arg to torch.nn.Sequitial. This change will not cause other conficts.
> 
> Although it is a little bit stupid, but easy enough. I used to set a individual environment for each projects.

Could you update your code to the latest version in order to be easily understand by readers? Thanks.

**Comment by qsyao** [comment]
It is worth to note that our method is focused on the adversarial attack on landmark detection, not the landmark detection methods. You can check the citation in our manuscript.

I have occurred recently. I am going to make the code cleaner later.  Some codes which are used for the comparative study are useless here.
